#name, main, version and api are required
name: QuelandiaPE
main: QuelandiaPE\MainClass
version: 1.0.0
api: [1.0.0]

load: POSTWORLD
author: Troy Ross
description: Quelandia Game Plugin
website: https://github.com/Quelab/QuelandiaPE
commands:
 steal_item:
  description: Give item to theif from victim
  usage: "Usage: /steal_item <thief> <victim>"
  permission: exampleplugin.command.steal_item
permissions:
 exampleplugin.command.steal_item:
  description: "Allows the user to run the example command"
  default: true